import Head from 'next/head';
import Link from 'next/link';
import styles from '../styles/Home.module.css';
import Cookies from 'js-cookie';
import { useEffect } from 'react';

export default function Home() {
	Cookies.set("cookie", "Harshil");

	useEffect(() => {
		if (window) {
			localStorage.setItem("localVariable", "123");
		}
	}, []);

	return (
		<div className={styles.container}>
			<Head>
				<title>Next JS Demo App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<Link href={'/products'} style={{color: 'blue'}}><u>Go to Products</u></Link> <br />
			<Link href={'/demo'} style={{color: 'blue'}}><u>Go to Demo</u></Link>
		</div>
	)
}
